# Jekyll configuration

name: my.entire.website
title: my.entire.website
description: Welcome to my entire website!

# url is currently only used only for the RSS feed in feed.xml
url: my.entire.website

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B %-d, %Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]

# Disqus
disqus: my-entire-website

# Google Analytics
google_analytics: UA-119869341-1

# Social media/stuff
twitter: https://twitter.com/kylemsguy
github: https://github.com/kylemsguy
fedi: https://what.entire.website/kylemsguy
